# Generated by Django 5.2.16 on 2026-08-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.Field(blank=True, null=True)),
            ],
            options={
                'db_table': 'Perfil',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CadastroTeste',
        ),
    ]
