# Generated by Django 5.2.16 on 2026-08-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfil_delete_cadastroteste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
