# Generated by Django 5.2.16 on 2026-08-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pet_delete_perfil'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pet',
            table='Pet',
        ),
    ]
